# Generated by Django 2.2.2 on 2019-06-28 22:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoMarco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'codigo_marco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('cp', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'colonia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('porcentaje_comision', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'comision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('referencias', models.TextField(blank=True, max_length=512, null=True)),
                ('entre_calles', models.TextField(blank=True, max_length=512, null=True)),
                ('estatus', models.BooleanField(default=True)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Colonia')),
            ],
            options={
                'db_table': 'direccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstatusPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estatus_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'etiqueta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('porcentaje_comision', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_original', models.ImageField(upload_to='foto_original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('foto_muestra', models.ImageField(upload_to='foto_muestra/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True)),
                ('alto', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('publica', models.BooleanField(default=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(related_name='fotografias_cat', to='config.Categoria')),
                ('etiquetas', models.ManyToManyField(related_name='fotografias_tags', to='config.Etiqueta')),
            ],
            options={
                'db_table': 'fotografia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='config.Usuario')),
            ],
            options={
                'db_table': 'fotografo',
                'managed': True,
            },
            bases=('config.usuario',),
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('profundidad', models.FloatField()),
                ('peso', models.FloatField()),
                ('precio', models.FloatField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.CodigoMarco')),
            ],
            options={
                'db_table': 'marco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MariaLuisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('precio', models.FloatField()),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
            ],
            options={
                'db_table': 'maria_luisa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModeloMariaLuisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('modelo', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'modelo_maria_luisa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('oxxo_order', models.CharField(max_length=12)),
                ('num_guia', models.CharField(blank=True, max_length=12, null=True)),
                ('peso', models.FloatField(default=0)),
                ('costo_envio', models.FloatField()),
                ('order_id', models.CharField(blank=True, max_length=512, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Comision')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Direccion')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusPago')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.FormaPago')),
            ],
            options={
                'db_table': 'orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'orientacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reaccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'red_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tamanio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tamanio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoComision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_comision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'tipo_foto',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='confiable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UsuarioRedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.RedSocial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario')),
            ],
            options={
                'db_table': 'usuario_has_red_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimos_digitos', models.CharField(max_length=5)),
                ('token', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=128)),
                ('nombre_propietario', models.CharField(max_length=256)),
                ('estatus', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario')),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiguiendoFotografo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fotografo', to='config.Fotografo')),
                ('siguiendo_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='siguiendo_a', to='config.Fotografo')),
            ],
            options={
                'db_table': 'siguiendo_fotografo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus_pago_fotografo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusPago')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Fotografia')),
                ('marco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Marco')),
                ('maria_luisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.MariaLuisa')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='config.Orden')),
                ('tipo_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoCompra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario')),
            ],
            options={
                'db_table': 'preferencias',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tarjeta'),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('cat_mun_id', models.IntegerField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Estado')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='marialuisa',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.ModeloMariaLuisa'),
        ),
        migrations.AddField(
            model_name='marialuisa',
            name='tamanio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tamanio'),
        ),
        migrations.AddField(
            model_name='marco',
            name='tamanio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tamanio'),
        ),
        migrations.CreateModel(
            name='FotoReaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Fotografia')),
                ('reaccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Reaccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Fotografo')),
            ],
            options={
                'db_table': 'foto_reaccion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fotografia',
            name='orientacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Orientacion'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='tamanio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tamanio'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='tipo_foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoFoto'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Pais'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario'),
        ),
        migrations.CreateModel(
            name='DimensionOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('profundidad', models.FloatField()),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Orden')),
            ],
            options={
                'db_table': 'dimension_orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('no_descargas_disponibles', models.PositiveIntegerField(default=3)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='colonia',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Municipio'),
        ),
        migrations.CreateModel(
            name='BitacoraLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pass_correcto', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Usuario')),
            ],
            options={
                'db_table': 'bitacora_login',
                'managed': True,
            },
        ),
    ]
