# Generated by Django 2.2.2 on 2019-07-02 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_codigomarco_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'managed': True,
                'db_table': 'tipo_papel',
            },
        ),
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'managed': True,
                'db_table': 'tipo_promocion',
            },
        ),
        migrations.AlterModelOptions(
            name='descarga',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='descarga',
            table='descarga',
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_promocion', models.CharField(max_length=8, unique=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('porcentaje_cantidad', models.FloatField()),
                ('imagen', models.ImageField(upload_to='promo_fotoferta/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.FormaPago')),
                ('marco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Marco')),
                ('maria_luisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.MariaLuisa')),
                ('tamanio_marco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tamanio')),
                ('tipo_compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoCompra')),
                ('tipo_promocion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoPromocion')),
            ],
            options={
                'managed': True,
                'db_table': 'promocion',
            },
        ),
    ]
