# Generated by Django 2.2.2 on 2019-07-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20190702_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_papel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoPapel'),
        ),
    ]
