# Generated by Django 2.2.2 on 2019-07-02 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20190702_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='marco',
            name='grosor_final',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marco',
            name='grosor_lado',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marco',
            name='grosor_total',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marco',
            name='imagen',
            field=models.ImageField(default='img', upload_to='img_marco/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
            preserve_default=False,
        ),
    ]
