# Generated by Django 2.2.2 on 2019-07-02 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20190702_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marco',
            old_name='imagen',
            new_name='imagen_horizontal',
        ),
        migrations.AddField(
            model_name='marco',
            name='imagen_vertical',
            field=models.ImageField(default='imagen_vertical', upload_to='img_marco/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
            preserve_default=False,
        ),
    ]
