# Generated by Django 2.2.2 on 2019-07-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20190702_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrosorPapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.FloatField()),
            ],
            options={
                'db_table': 'grosor_papel',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tipopapel',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipopapel',
            name='grosor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.GrosorPapel'),
            preserve_default=False,
        ),
    ]
