# Generated by Django 2.2.2 on 2019-07-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20190703_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to='img_texturas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
            ],
            options={
                'managed': True,
                'db_table': 'textura',
            },
        ),
        migrations.RemoveField(
            model_name='marialuisa',
            name='modelo',
        ),
        migrations.AddField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(default='promo', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='total_cupones',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='usos_por_usuario',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModeloMariaLuisa',
        ),
    ]
