# Generated by Django 2.2.2 on 2019-07-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_remove_marialuisa_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloMariaLuisa',
        ),
    ]
