# Generated by Django 2.2.2 on 2019-07-03 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_delete_modelomarialuisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMariaLuisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'managed': True,
                'db_table': 'modelo_maria_luisa',
            },
        ),
        migrations.AddField(
            model_name='marialuisa',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.ModeloMariaLuisa'),
            preserve_default=False,
        ),
    ]
