# Generated by Django 2.2.2 on 2019-07-03 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20190703_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
            ],
            options={
                'managed': True,
                'db_table': 'logo',
            },
        ),
        migrations.CreateModel(
            name='MenuFotopartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=256)),
            ],
            options={
                'managed': True,
                'db_table': 'menu_fotopartner',
            },
        ),
    ]
