# Generated by Django 2.2.2 on 2019-07-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_logo_menufotopartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografo',
            name='fotopartner',
            field=models.BooleanField(default=False),
        ),
    ]
