# Generated by Django 2.2.2 on 2019-07-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_personaladministrativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='calle', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='num_interior',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
