# Generated by Django 2.2.2 on 2019-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_auto_20190705_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marco',
            name='codigo',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
