# Generated by Django 2.2.2 on 2019-07-10 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_auto_20190705_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelomarialuisa',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelomarialuisa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelomarialuisa',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelomarialuisa',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
