# Generated by Django 2.2.2 on 2019-07-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_auto_20190705_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='nombre',
            field=models.CharField(default='Foto', max_length=64),
            preserve_default=False,
        ),
    ]
