# Generated by Django 2.2.2 on 2019-07-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_auto_20190710_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
