# Generated by Django 2.2.2 on 2019-07-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_promocion_estatus'),
        ('config', '0023_fotografia_nombre'),
    ]

    operations = [
    ]
