# Generated by Django 2.2.2 on 2019-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_auto_20190711_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(max_length=256)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=32)),
            ],
            options={
                'db_table': 'contactanos',
                'managed': True,
            },
        ),
    ]
