# Generated by Django 2.2.2 on 2019-07-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_auto_20190711_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_papel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PapelImpresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
                ('precio', models.FloatField()),
                ('tamanio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tamanio')),
                ('tipo_papel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoPapel')),
            ],
            options={
                'db_table': 'papel_impresion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='papel_impresion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.PapelImpresion'),
        ),
    ]
