# Generated by Django 2.2.2 on 2019-07-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_auto_20190711_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papelimpresion',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='papelimpresion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='papelimpresion',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='papelimpresion',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='papelimpresion',
            name='nombre',
        ),
    ]
