# Generated by Django 2.2.2 on 2019-07-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_papelimpresion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FotoPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('estatus', models.BooleanField(default=True)),
                ('tamanio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Tamanio')),
            ],
            options={
                'managed': True,
                'db_table': 'foto_precio',
            },
        ),
    ]
