# Generated by Django 2.2.2 on 2019-07-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_auto_20190712_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipofoto',
            name='precio',
        ),
        migrations.AddField(
            model_name='fotoprecio',
            name='tipo_foto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.TipoFoto'),
            preserve_default=False,
        ),
    ]
