# Generated by Django 2.2.2 on 2019-07-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_auto_20190712_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'managed': True,
                'db_table': 'estatus_compra',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='estatus_compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusCompra'),
            preserve_default=False,
        ),
    ]
