# Generated by Django 2.2.2 on 2019-07-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_auto_20190722_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Direccion'),
        ),
    ]
