# Generated by Django 2.2.2 on 2019-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0035_auto_20190722_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='oxxo_order',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
