# Generated by Django 2.2.2 on 2019-07-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_auto_20190722_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusPago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.FormaPago'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estatus_pago_fotografo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusPago'),
        ),
    ]
