# Generated by Django 2.2.2 on 2019-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_auto_20190722_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanio',
            name='alto',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanio',
            name='ancho',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanio',
            name='area',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
