# Generated by Django 2.2.2 on 2019-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_auto_20190730_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoprecio',
            name='max_altura',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoprecio',
            name='max_ancho',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoprecio',
            name='max_area',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoprecio',
            name='min_altura',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoprecio',
            name='min_ancho',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoprecio',
            name='min_area',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
