# Generated by Django 2.2.2 on 2019-08-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0042_auto_20190808_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
