# Generated by Django 2.2.2 on 2019-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0043_auto_20190808_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='costo_envio',
            field=models.FloatField(default=0),
        ),
    ]
