# Generated by Django 2.2.2 on 2019-08-12 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0046_auto_20190809_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='foto_home',
            field=models.ImageField(default='foto_home', upload_to='foto_home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
            preserve_default=False,
        ),
    ]
