# Generated by Django 2.2.2 on 2019-08-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0047_fotografia_foto_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
