# Generated by Django 2.2.2 on 2019-08-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0049_auto_20190815_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estatus_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pago_cliente', to='config.EstatusPago'),
        ),
    ]
