# Generated by Django 2.2.2 on 2019-08-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0050_producto_estatus_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
