# Generated by Django 2.2.2 on 2019-08-21 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0051_fotografia_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoreaccion',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
