# Generated by Django 2.2.2 on 2019-08-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0052_fotoreaccion_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografo',
            name='seguidores',
            field=models.BigIntegerField(default=0),
        ),
    ]
