# Generated by Django 2.2.2 on 2019-08-22 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0053_fotografo_seguidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarga',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descarga',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descarga',
            name='no_descargas_disponibles',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
