# Generated by Django 2.2.2 on 2019-08-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0054_auto_20190822_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarga',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Orden'),
            preserve_default=False,
        ),
    ]
