# Generated by Django 2.2.2 on 2019-08-26 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0058_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Genero'),
            preserve_default=False,
        ),
    ]
