# Generated by Django 2.2.2 on 2019-09-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0061_fotografia_num_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
