# Generated by Django 2.2.2 on 2019-09-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_motivoreporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actioner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Fotografo')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Fotografia')),
                ('reaccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Reaccion')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='config.Fotografo')),
            ],
            options={
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
    ]
