# Generated by Django 2.2.2 on 2019-09-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0066_auto_20190905_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='oxxo_order',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
